// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: deliveries.proto

package pb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type InvalidDeliveriesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InvalidDeliveriesRequest) Reset() {
	*x = InvalidDeliveriesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deliveries_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InvalidDeliveriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidDeliveriesRequest) ProtoMessage() {}

func (x *InvalidDeliveriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deliveries_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidDeliveriesRequest.ProtoReflect.Descriptor instead.
func (*InvalidDeliveriesRequest) Descriptor() ([]byte, []int) {
	return file_deliveries_proto_rawDescGZIP(), []int{0}
}

type InvalidDeliveriesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Deliveries []*Delivery `protobuf:"bytes,1,rep,name=deliveries,proto3" json:"deliveries,omitempty"`
}

func (x *InvalidDeliveriesResponse) Reset() {
	*x = InvalidDeliveriesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deliveries_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InvalidDeliveriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidDeliveriesResponse) ProtoMessage() {}

func (x *InvalidDeliveriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deliveries_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidDeliveriesResponse.ProtoReflect.Descriptor instead.
func (*InvalidDeliveriesResponse) Descriptor() ([]byte, []int) {
	return file_deliveries_proto_rawDescGZIP(), []int{1}
}

func (x *InvalidDeliveriesResponse) GetDeliveries() []*Delivery {
	if x != nil {
		return x.Deliveries
	}
	return nil
}

type Delivery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SupplierId string `protobuf:"bytes,1,opt,name=supplier_id,json=supplierId,proto3" json:"supplier_id,omitempty"`
	DriverId   string `protobuf:"bytes,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
}

func (x *Delivery) Reset() {
	*x = Delivery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deliveries_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Delivery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delivery) ProtoMessage() {}

func (x *Delivery) ProtoReflect() protoreflect.Message {
	mi := &file_deliveries_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delivery.ProtoReflect.Descriptor instead.
func (*Delivery) Descriptor() ([]byte, []int) {
	return file_deliveries_proto_rawDescGZIP(), []int{2}
}

func (x *Delivery) GetSupplierId() string {
	if x != nil {
		return x.SupplierId
	}
	return ""
}

func (x *Delivery) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

var File_deliveries_proto protoreflect.FileDescriptor

var file_deliveries_proto_rawDesc = []byte{
	0x0a, 0x10, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x1a, 0x0a, 0x18, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x49, 0x0a, 0x19, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x44, 0x65, 0x6c,
	0x69, 0x76, 0x65, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2c, 0x0a, 0x0a, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72,
	0x79, 0x52, 0x0a, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x69, 0x65, 0x73, 0x22, 0x48, 0x0a,
	0x08, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x75, 0x70,
	0x70, 0x6c, 0x69, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x73, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x72,
	0x69, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64,
	0x72, 0x69, 0x76, 0x65, 0x72, 0x49, 0x64, 0x32, 0x72, 0x0a, 0x18, 0x49, 0x6e, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x69, 0x65, 0x73, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x56, 0x0a, 0x15, 0x46, 0x69, 0x6e, 0x64, 0x49, 0x6e, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x69, 0x65, 0x73, 0x12, 0x1c, 0x2e, 0x70,
	0x62, 0x2e, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72,
	0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x62, 0x2e,
	0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x69, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_deliveries_proto_rawDescOnce sync.Once
	file_deliveries_proto_rawDescData = file_deliveries_proto_rawDesc
)

func file_deliveries_proto_rawDescGZIP() []byte {
	file_deliveries_proto_rawDescOnce.Do(func() {
		file_deliveries_proto_rawDescData = protoimpl.X.CompressGZIP(file_deliveries_proto_rawDescData)
	})
	return file_deliveries_proto_rawDescData
}

var file_deliveries_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_deliveries_proto_goTypes = []interface{}{
	(*InvalidDeliveriesRequest)(nil),  // 0: pb.InvalidDeliveriesRequest
	(*InvalidDeliveriesResponse)(nil), // 1: pb.InvalidDeliveriesResponse
	(*Delivery)(nil),                  // 2: pb.Delivery
}
var file_deliveries_proto_depIdxs = []int32{
	2, // 0: pb.InvalidDeliveriesResponse.deliveries:type_name -> pb.Delivery
	0, // 1: pb.InvalidDeliveriesService.FindInvalidDeliveries:input_type -> pb.InvalidDeliveriesRequest
	1, // 2: pb.InvalidDeliveriesService.FindInvalidDeliveries:output_type -> pb.InvalidDeliveriesResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_deliveries_proto_init() }
func file_deliveries_proto_init() {
	if File_deliveries_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_deliveries_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InvalidDeliveriesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deliveries_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InvalidDeliveriesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deliveries_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Delivery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_deliveries_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_deliveries_proto_goTypes,
		DependencyIndexes: file_deliveries_proto_depIdxs,
		MessageInfos:      file_deliveries_proto_msgTypes,
	}.Build()
	File_deliveries_proto = out.File
	file_deliveries_proto_rawDesc = nil
	file_deliveries_proto_goTypes = nil
	file_deliveries_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// InvalidDeliveriesServiceClient is the client API for InvalidDeliveriesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InvalidDeliveriesServiceClient interface {
	FindInvalidDeliveries(ctx context.Context, in *InvalidDeliveriesRequest, opts ...grpc.CallOption) (*InvalidDeliveriesResponse, error)
}

type invalidDeliveriesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInvalidDeliveriesServiceClient(cc grpc.ClientConnInterface) InvalidDeliveriesServiceClient {
	return &invalidDeliveriesServiceClient{cc}
}

func (c *invalidDeliveriesServiceClient) FindInvalidDeliveries(ctx context.Context, in *InvalidDeliveriesRequest, opts ...grpc.CallOption) (*InvalidDeliveriesResponse, error) {
	out := new(InvalidDeliveriesResponse)
	err := c.cc.Invoke(ctx, "/pb.InvalidDeliveriesService/FindInvalidDeliveries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InvalidDeliveriesServiceServer is the server API for InvalidDeliveriesService service.
type InvalidDeliveriesServiceServer interface {
	FindInvalidDeliveries(context.Context, *InvalidDeliveriesRequest) (*InvalidDeliveriesResponse, error)
}

// UnimplementedInvalidDeliveriesServiceServer can be embedded to have forward compatible implementations.
type UnimplementedInvalidDeliveriesServiceServer struct {
}

func (*UnimplementedInvalidDeliveriesServiceServer) FindInvalidDeliveries(context.Context, *InvalidDeliveriesRequest) (*InvalidDeliveriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindInvalidDeliveries not implemented")
}

func RegisterInvalidDeliveriesServiceServer(s *grpc.Server, srv InvalidDeliveriesServiceServer) {
	s.RegisterService(&_InvalidDeliveriesService_serviceDesc, srv)
}

func _InvalidDeliveriesService_FindInvalidDeliveries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvalidDeliveriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvalidDeliveriesServiceServer).FindInvalidDeliveries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.InvalidDeliveriesService/FindInvalidDeliveries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvalidDeliveriesServiceServer).FindInvalidDeliveries(ctx, req.(*InvalidDeliveriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _InvalidDeliveriesService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.InvalidDeliveriesService",
	HandlerType: (*InvalidDeliveriesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindInvalidDeliveries",
			Handler:    _InvalidDeliveriesService_FindInvalidDeliveries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "deliveries.proto",
}
